---
title: "Untitled"
output:
  word_document: default
  html_document: default
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(lubridate)
library(ggplot2)
library(dplyr)
library(tidyr)
library(knitr)

```

Read

```{r Read, include=TRUE, echo=FALSE}

fileFolder <- "C:\\GitHubRepos\\FodderBeetRUE_2016\\"

# read raw data
info <- read.table(paste0(fileFolder, "RUE.txt"), header = TRUE)

str(info)

info$N_Treatments <- as.factor(info$N_Treatments)
info$Date <- dmy(info$Date )
info$Total_DM <- info$Total_DM*100 # kg/ha to g/m2

summary(info)

df_x <- info %>%
  mutate(RUE=Total_DM/Interception)

```

```{r}
# read RUE calculated from raw data
rue_norm <- read.csv(paste0(fileFolder, "RUE_Normalised.csv"))

 rue_norm$N_treat <- as.factor(rue_norm$N_treat)
 rue_norm$W_treat <- as.factor(rue_norm$W_treat)
# rue_norm$Rep <- as.factor(rue_norm$Rep)
# info$Total_DM <- info$Total_DM*100 # kg/ha to g/m2
 
str(rue_norm)

summary(rue_norm)
```

```{r, echo=FALSE}
head(rue_norm)
```



```{r RUE_NNI}

# get RUEnorm per treat and create common index
df_rue <- rue_norm %>% 
  dplyr::select(Exp,N_treat,W_treat_lev, RUE_av) %>% 
  mutate(idMerge = paste0(Exp,"_",N_treat,"_",W_treat_lev)) 

# get average NNI per treat and create common index
df_nni <- info %>%
#  filter(Stage == "final") %>% # use only final harvest data as per RUE df FIXME: Should we use average?
  group_by(Experiment,N_Treatments,Water_treat_level) %>%
  dplyr::select(NNI) %>%
  na.omit() %>%
  summarise_each(funs(median)) %>%
#  dplyr::select(Date, Experiment,N_Treatments,Water_treat_level, Rep, NNI) %>% 
  mutate(idMerge = paste0(Experiment,"_",N_Treatments,"_",Water_treat_level)) %>%
  dplyr::select(-Experiment,-N_Treatments,-Water_treat_level) # remove extra labels now

# merge RUEnorm with NNI
df_rue_nni <- merge(df_nni,df_rue, by = "idMerge" )

#df_rue_nni$Rep <- as.factor(df_rue_nni$Rep)

head(df_rue_nni)

```

```{r checkData}

summary(df_rue_nni)

#df_rue_nni %>% filter(is.na(NNI))

```

```{r}
# check
df_rue_nni %>%
  ggplot(aes(x=N_treat, y=NNI, colour=Exp)) +
  geom_jitter() +
  geom_boxplot(alpha=0.2)

```

```{r}

df_rue_nni %>%
 # filter(W_treat_lev == "ET100_1w") %>% #  fullwater
  ggplot(aes(x=N_treat, y=NNI,colour=Exp)) +
  geom_point()

```
 - Only use fullET because NNI is overestimated in water-stressed crops

```{r NNI_RUE_Graph, warning=FALSE}

# FIXME: This does not match emmanuel's data in excel needs checking

xBreak = 1.1 # FIXME: just to test

dfNNI <- df_rue_nni %>%
 # filter(W_treat_lev == "ET100_1w") %>% # FIXME: is it better to use Potential (i.e. add some extra treats? - no because only C and it has no N treats)
 # filter(Exp != "W-") %>%
#  filter(W_treat_lev == "fullET") %>%  
  na.omit() %>%
  # group_by(Exp) %>%
  # mutate(RUEnorm = RUE/max(RUE)) %>%
  # ungroup()%>%
  group_by(Exp,N_treat,W_treat_lev) %>%
  summarise_each(funs(mean, sd)) 


graphNNI <- df_rue_nni %>% 
 #  filter(Exp != "W-", W_treat_lev == "ET100_1w") %>%
  ggplot(aes(x=NNI, y=RUE_av)) +
#  geom_smooth(method="lm") +
  geom_smooth(method='lm') +
  geom_point(aes(colour=N_treat, shape=Exp), size=2) +
    # geom_errorbar(aes(ymin=RUEnorm_mean-RUEnorm_sd/2,
    #                 ymax=RUEnorm_mean+RUEnorm_sd/2), width = 0.0, colour = "darkgrey") +
    # geom_errorbarh(aes(xmin=NNI_mean-NNI_sd/2,
    #                 xmax=NNI_mean+NNI_sd/2), colour = "darkgrey") +
#  ylim(0.7, 1.05) +
    ylim(0, 4) +
  ylab("Radiation use efficiency (0-1) ") +
  xlab("Nitrogen Nutrition Index (NNI)") +
  # geom_segment(aes(x=0.85,xend=1.0,y=2.8,yend=3.5), linetype=2) +
  # geom_segment(aes(x=1.0,xend=1.5,y=3.5,yend=3.5), linetype=2) +
  theme(legend.title=element_blank())+ theme(legend.position="top")# +
#  facet_grid(.~Exp)

graphNNI
#+
 # geom_segment(aes(x = min(NNI), xend = xBreak, y = 0.75, yend = 1), 
 #              linetype=1, colour ="black", size=1.2)# +
 # geom_segment(aes(x = xBreak, xend = max(NNI), y = 1, yend = 1), linetype=1, colour ="black", size=1.2)
  
```


# find coefficients

```{r}
df <- dfNNI %>% 
  as.data.frame() %>%
  mutate(RUEnorm_mean = as.numeric(RUE_av_mean)) %>%
  mutate(NNI_mean = as.numeric(as.character(NNI_mean))) %>%
  dplyr::select(RUEnorm_mean, NNI_mean) 

mod = (lm(RUEnorm_mean ~ NNI_mean, data = df)) 

print(paste0("Intercept: ",summary(mod)$coeff[1]))  
print(paste0("Slope: ",summary(mod)$coeff[2])) 
print(paste0("R2: ",summary(mod)$r.squared)) 
print(paste0("Pvalue: ",summary(mod)$coeff[8])) 

```




```{r}

# Multiple plot function
#
# ggplot objects can be passed in ..., or to plotlist (as a list of ggplot objects)
# - cols:   Number of columns in layout
# - layout: A matrix specifying the layout. If present, 'cols' is ignored.
#
# If the layout is something like matrix(c(1,2,3,3), nrow=2, byrow=TRUE),
# then plot 1 will go in the upper left, 2 will go in the upper right, and
# 3 will go all the way across the bottom.
#
multiplot <- function(..., plotlist=NULL, file, cols=1, layout=NULL) {
  library(grid)

  # Make a list from the ... arguments and plotlist
  plots <- c(list(...), plotlist)

  numPlots = length(plots)

  # If layout is NULL, then use 'cols' to determine layout
  if (is.null(layout)) {
    # Make the panel
    # ncol: Number of columns of plots
    # nrow: Number of rows needed, calculated from # of cols
    layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                    ncol = cols, nrow = ceiling(numPlots/cols))
  }

 if (numPlots==1) {
    print(plots[[1]])

  } else {
    # Set up the page
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))

    # Make each plot, in the correct location
    for (i in 1:numPlots) {
      # Get the i,j matrix positions of the regions that contain this subplot
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))

      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
    }
  }
}

```

```{r, fig.height=4, fig.width=10}

# this needs to be run with the RUE norm script to work to have graph in memory - FIXME

# multiplot(graphRUEnorm,graphNNI,cols=2)

```

