---
title: "RUE Fodder Beet"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(lubridate)
library(ggplot2)
library(dplyr)
library(tidyr)
library(knitr)

```

Read

```{r Read, include=TRUE, echo=FALSE}

fileFolder <- "C:\\GitHubRepos\\FodderBeetRUE_2016\\"

info <- read.table(paste0(fileFolder, "RUE.txt"), header = TRUE)

str(info)

info$N_Treatments <- as.factor(info$N_Treatments)
info$Date <- dmy(info$Date )
info$Total_DM <- info$Total_DM*100 # kg/ha to g/m2

summary(info)

```

```{r, echo=FALSE}
head(info)
```


```{r TimeSeries, echo=FALSE, warning=FALSE}

info %>%
 # dplyr::select(-Shoot_DM, -Bulb_DM) %>%
  tidyr::gather("Variable", "Value",11:12) %>%
  mutate(Variable = as.factor(Variable))  %>%
  group_by(Experiment, N_Treatments, Water_Treatments, Water_treat_level, Potential, Date, Variable) %>%
  summarise_each(funs(mean, sd)) %>%
  ggplot(aes(x=Date,y=Value_mean, 
             shape=factor(N_Treatments),
             colour=factor(Water_treat_level))) +
  geom_point() +
  geom_line() +
  facet_grid(Variable~Experiment, scales= "free") +
  ylab("Total biomass (g/m2)                 Intercepted light (MJ/m2) ") +
  xlab("Sampling date") +
  geom_errorbar(aes(ymin=Value_mean-Value_sd/2,
                    ymax=Value_mean+Value_sd/2), 
                width=0.25)
  
  
```

## Including Plots

```{r N_effect, echo=FALSE, warning=FALSE}

# biomass
info %>%
  filter(Stage == "final") %>%
  group_by(Experiment, N_Treatments, Water_Treatments, Water_treat_level, Potential) %>%
  summarise_each(funs(mean, sd)) %>%
  ggplot(aes(x=N_Treatments,y=Total_DM_mean, 
             shape=factor(Water_Treatments),
             colour=factor(Water_treat_level))) +
  geom_point() +
  ylab("Total biomass (g/m2) ") +
  xlab(" N rate (kg N/ha)") +
  geom_errorbar(aes(ymin=Total_DM_mean-Total_DM_sd/2,
                    ymax=Total_DM_mean+Total_DM_sd/2), 
                width=0.25) +
 # facet_wrap(Experiment~Potential, ncol=3)
   facet_grid(Potential~Experiment)



```

```{r, warning=FALSE}
# light interception
info %>%
  filter(Stage == "final") %>%
  group_by(Experiment, N_Treatments, Water_Treatments, Water_treat_level, Potential) %>%
  summarise_each(funs(mean, sd)) %>%
  ggplot(aes(x=N_Treatments,y=Interception_mean, 
             shape=factor(Water_Treatments),
             colour=factor(Water_treat_level))) +
  geom_point() +
  ylab("Intercepted light (MJ/m2) ") +
  xlab(" N rate (kg N/ha)") +
  geom_errorbar(aes(ymin=Interception_mean-Interception_sd/2,
                    ymax=Interception_mean+Interception_sd/2), 
                width=0.25) +
 # facet_wrap(Experiment~Potential, ncol=3)
   facet_grid(Potential~Experiment)
```




```{r pressure, echo=FALSE, echo=FALSE, warning=FALSE}

info %>%
 # dplyr::select(Date, N_Treatments, Water_Treatments,Total_DM,Interception)  %>%
  group_by(N_Treatments, Water_Treatments,Water_treat_level,Date, Potential) %>%
  mutate(Total_DM = Total_DM) %>% # from t/ha to g/m2
  summarise_each(funs(mean,sd)) %>%
  ggplot(aes(x=Interception_mean,y=Total_DM_mean, 
             shape=factor(N_Treatments),
             colour=factor(Water_treat_level))) +
  geom_point() +
  geom_smooth(method=lm, se=FALSE) +
  ylab("Total biomass (g/m2) ") +
  xlab(" Light interception (MJ/m2)") +
    geom_errorbar(aes(ymin=Total_DM_mean-Total_DM_sd/2,
                    ymax=Total_DM_mean+Total_DM_sd/2)) +
 # facet_wrap(~N_Treatments, ncol=3)
 facet_grid(.~Potential)


```


```{r RUECalc, echo=FALSE, warning=FALSE, include=TRUE}

# calculate RUE per plot

# head(info)

# create index for each rep (observation period and unit as a rueChunk)
info <- info %>%
mutate(rueChunk = paste0(Experiment,"_", 
                         N_Treatments,"_" ,
                         Water_treat_level,"_", 
                         Rep))

rounds <- unique(info$rueChunk)

# loop through all the individual periods/treats/experiments
resTable <- data.frame(NULL)

for(i in 1:length(rounds)) {
  
 thisStat <- NULL
  
 buf <- info[info$rueChunk == rounds[i],]
 
 meas <- buf$Total_DM 
 sim  <- buf$Interception
  
  n_s <- length(sim)
  n_m <- length(meas)
  model <- lm(meas~sim)
  sim_sq <- sum((sim - mean(sim))^2)
  mes_sq <- sum((meas - mean(meas))^2)
  r2 <- summary(model)$r.squared
  slope <- model$coefficients[[2]]
  int <- model$coefficients[[1]]
  
 thisStat <- data.frame(Exp = buf$Experiment[1], 
                        N_treat = buf$N_Treatments[1], 
                        W_treat = buf$Water_Treatments[1],
                        W_treat_lev = buf$Water_treat_level[1],
                        Rep = buf$Rep[1],
                        n = n_s,
                        RUE = slope, 
                        intercept=int, 
                        R2=r2)
 
 if(i==1) {
   resTable <- thisStat
 } else {
   resTable <- rbind(resTable,thisStat)
 }
}

resTable$Rep <- as.factor(resTable$Rep)
head(resTable)


# colnames(resTable) <- c("Experiment","N_Treatments", 
#                         "Water_Treatments", "Rep",
#                         "RUE", "Intercept", "R2")


```

```{r, echo=FALSE}
summary(resTable)
```

```{r}
resTable %>%
  kable(format = "markdown", digits = 2)
```

```{r, warning=FALSE}
# graph
resTable %>%
  group_by(N_treat, W_treat) %>%
  summarise_each(funs(mean, sd)) %>%
  ggplot(aes(x=N_treat, y=as.numeric(RUE_mean),
             shape=factor(W_treat),
             colour=factor(W_treat))) +
  geom_point(size = 2) +
  geom_line() +
  ylab("Radiation use efficiency (g/MJ) ") +
  xlab(" N rate (kg N/ha)")+
    geom_errorbar(aes(ymin=RUE_mean-RUE_sd/2,
                    ymax=RUE_mean+RUE_sd/2), width = 0.25) +
  ylim(2, 3)

```

```{r NormRUE}
# normalise within each experiment
rue_norm <- resTable %>%
  group_by(Exp) %>% # FIXME: not sure how to select the maximum here. Assuming it's treat
  mutate(RUEmax = max(RUE)) %>%
  ungroup() %>%
  mutate(RUEnorm = RUE/RUEmax) 

head(rue_norm)
```




```{r, warning=FALSE}
rue_norm %>%
  group_by(N_treat, W_treat_lev,Exp) %>%
  summarise_each(funs(mean, sd)) %>%
  ggplot(aes(x=N_treat, y=as.numeric(RUEnorm_mean),
             shape=factor(Exp),
             colour=factor(W_treat_lev))) +
  geom_point(size = 2) +
  geom_line() +
  ylab("Normalised radiation use efficiency (0-1) ") +
  xlab(" N rate (kg N/ha)")+
    geom_errorbar(aes(ymin=RUEnorm_mean-RUEnorm_sd/2,
                    ymax=RUEnorm_mean+RUEnorm_sd/2), width = 0.25) +
  ylim(0.5, 1)
```



```{r RUE_NNI}

# get RUE per plot and common index
df_rue <- rue_norm %>% 
  dplyr::select(Exp,N_treat,W_treat_lev,Rep, RUEnorm, RUE) %>% 
  mutate(idMerge = paste0(Exp,"_",N_treat,"_",W_treat_lev,"_",Rep)) 

# get NNI per plot and common index
df_nni <- info %>%
  filter(Stage== "final") %>% # use only final harvest data as per RUE df
  dplyr::select(Experiment,N_Treatments,Water_treat_level, Rep, NNI) %>% 
  mutate(idMerge = paste0(Experiment,"_",N_Treatments,"_",Water_treat_level,"_",Rep)) %>%
  dplyr::select(-Experiment,-N_Treatments,-Water_treat_level, -Rep) # remove extra labels now

df_rue_nni <- merge(df_nni,df_rue, by = "idMerge" )

df_rue_nni$Rep <- as.factor(df_rue_nni$Rep)

head(df_rue_nni)

```

```{r checkData}

summary(df_rue_nni)

```

```{r}

df_rue_nni %>%
  ggplot(aes(x=N_treat, y=NNI, colour=Exp)) +
  geom_jitter() +
  geom_boxplot(alpha=0.2)

```

```{r}

df_rue_nni %>%
  filter(W_treat_lev == "fullET") %>%
  ggplot(aes(x=N_treat, y=NNI,colour=Exp)) +
  geom_jitter(aes(width=0.2)) +
  geom_boxplot(alpha=0.2)

```


```{r NNI_RUE_Graph, warning=FALSE}

# FIXME: This does not match emmanuel's data in excel needs checking

xBreak = 1.1 # FIXME: just to test

df_rue_nni %>%
  filter(W_treat_lev == "fullET") %>%
  na.omit() %>%
  group_by(Exp,N_treat,W_treat_lev) %>%
  summarise_each(funs(mean)) %>%
  ggplot(aes(x=NNI, y=RUEnorm, colour=N_treat, shape=W_treat_lev)) +
  geom_point() +
  geom_segment(aes(x = min(NNI), xend = xBreak, y = 0.75, yend = 1), 
               linetype=1, colour ="black", size=1.2) +
  geom_segment(aes(x = xBreak, xend = max(NNI), y = 1, yend = 1), linetype=1, colour ="black", size=1.2)
  
```


ANOVA RUE

```{r ANOVA, echo=FALSE}

str(resTable)

exp <- unique(resTable$Exp)


for(e in 1:length(exp)) {
  
  if(e == 1) {
    
anova <- NULL
df <- NULL
df <- resTable %>% subset(Exp == exp[e])

anova <- aov(RUE ~ N_treat+Rep, data = df)
print("############## EXP A ##############")
print(" ")
print(summary(anova))
print(TukeyHSD(anova))

    
  } else if ( e == 2) {
    
anova <- NULL
df <- NULL
df <- resTable %>% subset(Exp == exp[e])
 
  
anova <- aov(RUE ~ N_treat*W_treat_lev+Rep, data = df)
print("############## EXP B ##############")
print(" ")
print(summary(anova))
print(TukeyHSD(anova))
    
  }  else if (e == 3) {
    
anova <- NULL
df <- NULL
df <- resTable %>% subset(Exp == exp[e])

anova <- aov(RUE ~ W_treat_lev+Rep, data = df)
print("############## EXP C ##############")
print(" ")
print(summary(anova))
print(TukeyHSD(anova))
    
  }
  
}

```

For RUE vs NNI 

* Water_treat_level == "fullET"
* 


```{r Partitioning}

# info %>%
#   group_by(Experiment, N_Treatments, Water_Treatments, Water_treat_level, Potential, Date) %>%
#   dplyr::select(Shoot_DM, Bulb_DM) %>%
#   summarise_each(funs(mean, sd)) %>%
#   tidyr::gather("Variable", "Value",7:8) %>%
#   ggplot(aes(x=Date,y=Value)) +
#   geom_area(aes(colour=Variable)) +
#   facet_grid(.~Experiment, scales= "free") +
#   ylab("Total biomass (g/m2)                 Intercepted light (MJ/m2) ") +
#   xlab("Sampling date") +
#   geom_errorbar(aes(ymin=Value_mean-Value_sd/2,
#                     ymax=Value_mean+Value_sd/2), 
#                 width=0.25)

# make it reproducible
# set.seed(1492)
# Sector <- rep(c("S01","S02","S03","S04","S05","S06","S07"),times=7)
# Year <- rep(c("1950","1960","1970","1980","1990","2000","2010"),each=7)
# Value <- runif(49, 10, 100)
# df <- data.frame(Sector,Year,Value)
# 
# gg <- ggplot(df, aes(x=as.numeric(as.character(Year)), y=Value))
# gg <- gg + geom_area(aes(colour=Sector, fill=Sector))
# gg


```


